### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by hexadecimal-berry** [Lenni0451/SpigotPluginManager#1]
https://i.imgur.com/inzLS4T.png
Server Version: 1.8

ViaVersion: 1.8-1.15

Plugin continues to run, but wanted to share that issue.

**Comment by Lenni0451** [comment]
Hey, thanks for the info. It seems like 1.8.0 spigot does not have gson included. I updated the info on Spigotmc. If you want to use it and have full feature support you have to install [Gson-Spigot](https://www.spigotmc.org/resources/gson-spigot.72187/).
