### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Legit4K** [Lenni0451/SpigotPluginManager#10]
Can the plugin update tasks run on their own thread? At the moment, they hang the server until the operation is complete so when there's more than 10 plugins it causes the server to stall.

**Comment by Lenni0451** [comment]
Am I right that you mean the '/pm update' command?

**Comment by Legit4K** [comment]
Yeah

**Comment by Lenni0451** [comment]
Yes that is possible. But reloading the plugin has to be sync I think. I will add that as soon as I am done with translations

**Comment by Legit4K** [comment]
Alright thanks, btw did something change in 1.17 to break the `/pm download` command? Both direct and spigot options don't seem to work on the latest version, it just says the plugin could not be found or has no download when it definitely does (for spigot option, u can test it on `https://www.spigotmc.org/resources/playtimes-check-players-playtime-server-uptime.58858/`)

**Comment by Lenni0451** [comment]
Sam issue as #8

**Comment by Lenni0451** [comment]
#11 Fixed some issues with the spiget api. The plugin you tried to download now actually works

**Comment by Legit4K** [comment]
@Lenni0451 can u upload the released jar

**Comment by Lenni0451** [comment]
I will create a new release soon. I wanted to wait for an answer of someone else having problems but they don't seem to answer, so...

**Comment by Lenni0451** [comment]
I uploaded the new release

**Comment by Legit4K** [comment]
Thanks 👍

**Comment by Legit4K** [comment]
@Lenni0451 Hey, I noticed that it's not detecting new versions for some plugins that were downloaded using this plugin manager, for example the Suicide Plugin -> https://www.spigotmc.org/resources/suicide.80727/

Can you take a look?

**Comment by Lenni0451** [comment]
Are you intentionally trying to infect me or do you not know that this plugin contains a Virus?

**Comment by Lenni0451** [comment]
The downloader is working fine btw. The version in the plugin.yml was just not updated

**Comment by Lenni0451** [comment]
> 
> 
> @Lenni0451 Hey, I noticed that it's not detecting new versions for some plugins that were downloaded using this plugin manager, for example the Suicide Plugin -> https://www.spigotmc.org/resources/suicide.80727/
> 
> Can you take a look?

The plugins Suicide, Light and NoTotemHand of the same author are infected with the same virus. I have reported all of them

**Comment by Legit4K** [comment]
> > @Lenni0451 Hey, I noticed that it's not detecting new versions for some plugins that were downloaded using this plugin manager, for example the Suicide Plugin -> https://www.spigotmc.org/resources/suicide.80727/
> > Can you take a look?
> 
> The plugins Suicide, Light and NoTotemHand of the same author are infected with the same virus. I have reported all of them

Oh wow good to know, i just recently got the plugin and I was in a rush so I forgot to check the source code before using it so my bad

**Comment by Legit4K** [comment]
@Lenni0451 hmmm, I just tested it on an alternative plugin and it still fetches an old version (in this case v1.7 when the latest is 2.1)

I also checked its `plugin.yml` and it mentions 2.1 so idk why it fetches an old version still. It's the slashKill plugin -> https://www.spigotmc.org/resources/slashkill.68347/

**Comment by Lenni0451** [comment]
I manually downloaded it using the spiget api and I got the outdated version. So this is again a Spiget issue. Nothing I can do here

**Comment by Legit4K** [comment]
I see, maybe they cache versions but even still those updates have been out for a while 🤔

I'll go see if they can address the issue
