### ISSUE TITLE
Disable commands in game

### ISSUE THREAD

**Issue by LoneDespair** [Lenni0451/SpigotPluginManager#12]
Greetings!, this plugin looks really cool, but since its features can be very dangerous, it would be nice if there's a way to only allow execution via console, as people like me give away op like its a choco bar

**Comment by Lenni0451** [comment]
Not a bad idea. I will implemented that. (You should really think about some sort of permission system like LuckPerms)

**Comment by LoneDespair** [comment]
> Not a bad idea. I will implemented that. (You should really think about some sort of permission system like LuckPerms)

Awesome tysm!, (I do have luckperms, but find it very tedious to setup for every commands)

**Comment by Lenni0451** [comment]
I finished adding the config option. Took a bit since I had to add automatic translation updating.
I will not yet push a new release. I want to wait a bit.
It would be nice if you could check everything out and tell me if there are some bugs or unexpected behaviour.
[PluginManager.zip](https://github.com/Lenni0451/SpigotPluginManager/files/6988541/PluginManager.zip)

**Comment by LoneDespair** [comment]
> I finished adding the config option. Took a bit since I had to add automatic translation updating.
> I will not yet push a new release. I want to wait a bit.
> It would be nice if you could check everything out and tell me if there are some bugs or unexpected behaviour.
> [PluginManager.zip](https://github.com/Lenni0451/SpigotPluginManager/files/6988541/PluginManager.zip)

That was actually insanely quick (Wasn't expecting until like a week or two)

Only issue I noticed is that it doesn't update the old config, besides that it's perfect! (Will be using this version)

**Comment by Lenni0451** [comment]
Updating the config is not easily possible because the yaml parser will skip all comments when parsing and if I try to save the new config either all comments are gone or all settings resetted. I still hope to find a working solution

**Comment by Lenni0451** [comment]
Well gues what. I just found a working solution for that too.
You will have to wait for this until the release tho.
You should receive that update normally if it gets public. The auto updater should work too

**Comment by LoneDespair** [comment]
> Well gues what. I just found a working solution for that too.
> You will have to wait for this until the release tho.
> You should receive that update normally if it gets public. The auto updater should work too

That's really awesome, also did you just wrote 300+ lines of code in less than an hour? that's crazy fast
