### ISSUE TITLE
Shows "outdated" when using self-built jar.

### ISSUE THREAD

**Issue by lumii-uwu** [Lenni0451/SpigotPluginManager#17]
I built the 2.7.2 jar myself and now the plugin responds in the console with the following lines:
![image](https://user-images.githubusercontent.com/54220441/191768059-2b59dffe-49ed-44e8-a5fb-26b4bdffb3aa.png)
I don't think that this is intended. x3

**Comment by Lenni0451** [comment]
Just wanted to let you know that I added a `updatable` setting into the `gradle.properties` file.
![grafik](https://user-images.githubusercontent.com/20379977/191832199-215ae578-37a7-4737-a1aa-dcb28ea43e46.png)
