### ISSUE TITLE
Plugins in update folder don't get reloaded

### ISSUE THREAD

**Issue by vvMv** [Lenni0451/SpigotPluginManager#2]
When the bukkit, spigot, etc server starts, it will check the /plugins/update folder and override any new jars with the ones currently in the /plugins folder. When reloading a plugin via /pm reload <plugin> these jars do not get replaced with the old ones and the plugin will not be updated.
The updates folder is used by many plugins that have automatic updater systems so that the plugin will be reloaded when the server restarts. My request is to add this to PluginManager.

Thanks :)

**Comment by Lenni0451** [comment]
Thanks for the idea. I'll see what I can do

**Comment by Lenni0451** [comment]
I just added this. It will be in the next release.
A bit late but better than never I guess...
