### ISSUE TITLE
Is this something to report? not sure though

### ISSUE THREAD

**Issue by WolfLiSteel** [Lenni0451/SpigotPluginManager#20]
Is this something to report? not sure though

17.01 22:43:26 [Server] INFO PM | An unknown error occurred whilst checking for a new PluginManager version!.
17.01 22:43:26 [Server] WARN java.net.SocketException: Connection reset by peer
17.01 22:43:26 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
17.01 22:43:26 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
17.01 22:43:26 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
17.01 22:43:26 [Server] WARN at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.SSLSocketOutputRecord.flush(SSLSocketOutputRecord.java:271)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:89)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:646)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:529)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:251)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
17.01 22:43:26 [Server] WARN at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
17.01 22:43:26 [Server] WARN at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
17.01 22:43:26 [Server] WARN at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
17.01 22:43:26 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
17.01 22:43:26 [Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
17.01 22:43:26 [Server] WARN at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
17.01 22:43:26 [Server] WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
17.01 22:43:26 [Server] WARN at PluginManager.jar//net.lenni0451.spm.utils.DownloadUtils.openConnection(DownloadUtils.java:29)
17.01 22:43:26 [Server] WARN at PluginManager.jar//net.lenni0451.spm.utils.DownloadUtils.getNewestVersion(DownloadUtils.java:152)
17.01 22:43:26 [Server] WARN at PluginManager.jar//net.lenni0451.spm.PluginManager.lambda$checkUpdates$2(PluginManager.java:92)
17.01 22:43:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
17.01 22:43:26 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
17.01 22:43:26 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
17.01 22:43:26 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
17.01 22:43:26 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
17.01 22:43:26 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Lenni0451** [comment]
Hi. No, this is not worth reporting. The updater was just unable to connect to github. The plugin still works fine.
If you want to disable the update checker you can do so in the config file
