### ISSUE TITLE
Could not add plugin into config for later updates

### ISSUE THREAD

**Issue by monstergamer315** [Lenni0451/SpigotPluginManager#27]
As I download a plugin the message `Could not add plugin into config for later updates` appears in the console the following appears:
`25.03 12:26:51 [Server] INFO monstergamer315 issued server command: /pluginmanager download spigot https://www.spigotmc.org/resources/jobs-reborn.4216/ jobs-reborn.jar
25.03 12:26:52 [Server] WARN java.lang.UnsupportedOperationException
25.03 12:26:52 [Server] WARN at io.papermc.paper.plugin.manager.DummyBukkitPluginLoader.getPluginDescription(DummyBukkitPluginLoader.java:35)
25.03 12:26:52 [Server] WARN at PluginManager.jar//net.lenni0451.spm.commands.subs.Download_Sub.execute(Download_Sub.java:81)
25.03 12:26:52 [Server] WARN at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
25.03 12:26:52 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
25.03 12:26:52 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
25.03 12:26:52 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
25.03 12:26:52 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
25.03 12:26:52 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
25.03 12:26:52 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)`
As I don't see where I have done something wrong I think its an issue but I'm not sure.
I would very thank full for any help

**Comment by Lenni0451** [comment]
This is indeed an issue with PluginManager. I fixed it in the latest commit.
You can download the latest dev build from my [Jenkins Server](https://build.lenni0451.net/job/SpigotPluginManager/) and try it out.
