### ISSUE TITLE
Proper command documentation

### ISSUE THREAD

**Issue by JPenuchot** [Lenni0451/SpigotPluginManager#7]
None of the commands has a proper documentation, either on the Github, Spigot resource page, or Spigot command line. Makes it hard to use on remote computers.

**Comment by Lenni0451** [comment]
For me as the dev the commands are all self explanatory. It would be nice if you could provide me with an example so I really know what you mean and what things are too hard to understand.

**Comment by JPenuchot** [comment]
For the download command for example, I couldn't figure what the plugin ID meant and how I was supposed to find it until I got an error from the command explaining it, and I wasn't 100% sure what the purpose of the filename parameter was until I looked at the code. Making the commands a bit more verbose when you don't give them any parameter would be very nice for newbies.

**Comment by Lenni0451** [comment]
I added descriptions to all commands. I would be open for Feedback if it is not exactly what you imagined or I made a typo or something.
![grafik](https://user-images.githubusercontent.com/20379977/114908464-6a064200-9e1c-11eb-8def-16e019d4d625.png)

**Comment by Lenni0451** [comment]
Because it is actually a lot of spam in the chat I would only display it in the console

**Comment by JPenuchot** [comment]
> Because it is actually a lot of spam in the chat I would only display it in the console

It would be more time consuming I guess but many plugins deal with that by having dedicated documentation pages with a help command, for example `pm help download` could provide extensive docs. However more extensive docs could be put in the Spigot resource page or the Github repo itself for those who need it.

> I added descriptions to all commands. I would be open for Feedback if it is not exactly what you imagined or I made a typo or something.

It's pretty nice already! The only suggestion I'd have is adding "to the specified filename" for the download command.

**Comment by Lenni0451** [comment]
I like the idea of the dedicated help command. I think I'll add it with some extended details about the commands.
Could take a while because I have other things to do but I'll come back to you once I finished it.

**Comment by JPenuchot** [comment]
Great, thanks for your time!

**Comment by Lenni0451** [comment]
I actually had enough time to finish it directly. Took some time but it should be good now.
Here is a preview of the /pm download command:
![grafik](https://user-images.githubusercontent.com/20379977/114920488-c7ed5680-9e29-11eb-8d95-9639ee9c8929.png)
Not all commands have a description this large because what to say about an enable/disable command

**Comment by JPenuchot** [comment]
Looks perfect to me! Thanks a lot :)

**Comment by Lenni0451** [comment]
Great! I just pushed it. I will add another sub command and then I will create a release of the new version.
I'll close this issue now because the help is done.
