### ISSUE TITLE
Spigot downloader seems to be broken

### ISSUE THREAD

**Issue by JPenuchot** [Lenni0451/SpigotPluginManager#8]
Downloading [TimeVote](https://www.spigotmc.org/resources/timevote-1-7-1-16.7312/) along with other Spigot plugins doesn't seem to work. The command I used was `pluginmanager download spigot 7312 TimeVote.jar`, to which PluginManager responded `The plugin could not be found or has no download.` even though it does have a download attached to it.

**Comment by Lenni0451** [comment]
This is something I can sadly not fix. The spiget api I am using which provides the downloads can not find the plugin.
![grafik](https://user-images.githubusercontent.com/20379977/114905073-d5e6ab80-9e18-11eb-8235-e3abeb6b0ef2.png)

**Comment by JPenuchot** [comment]
Got it, thanks for the explanation :)

**Comment by JPenuchot** [comment]
Sorry to bother you about a closed issue but I've tried to test [Spiget's resource download enpoint](http://spiget.org/documentation/#!/resources/get_resources_resource_download) several times, for several plugins since the issue got closed, and it seems to be broken. I thought maybe an issue should be opened to find an alternative to Spiget for plugin download?

**Comment by Lenni0451** [comment]
If you have any alternative I could implement them. But I personally don't know any

**Comment by Legit4K** [comment]
Maybe u can look into https://github.com/Maximvdw/SpigotSite-API
