### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by ddaodan** [Lenni0451/SpigotPluginManager#9]
I want to translate the plugin into other languages
but this requires recompiling the plugin

**Comment by Lenni0451** [comment]
Adding translations for everything will take a while to implement it correctly. I will start tomorrow. Maybe it is faster than I thought.

**Comment by ddaodan** [comment]
> Adding translations for everything will take a while to implement it correctly. I will start tomorrow. Maybe it is faster than I thought.

Thanks!

**Comment by Lenni0451** [comment]
I finally finished the translations. I will release a new update soon after I fixed some more problems
I don't think that I will add many more translations so you can already start translating if you want.

**Comment by Lenni0451** [comment]
I created a new release containing the translation system
